version: "3.9"
services:
  node1:
    build:
      context: ./docker
      args:
        PUBKEY: ${PUBKEY}
    hostname: node1
    platform: linux/arm64
    ports:
      - "2221:22"
  node2:
    build:
      context: ./docker
      args:
        PUBKEY: ${PUBKEY}
    hostname: node2
    platform: linux/arm64
    ports:
      - "2222:22"